platform :ios, '10.0'
use_frameworks!

target :'SwiftDemo'  do

    pod 'Alamofire', '~> 4.2.0'
    pod 'SnapKit', '~> 4.0.0'
    pod 'SwiftyJSON', '~> 4.0.0'
    pod 'PromiseKit', '~> 6.0'
    pod 'Kingfisher', '~> 4.6'
    pod 'ImageViewer', '~> 5.0'
end


target 'RxSwiftDemo' do
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
end
