platform :ios, '10.0'
use_frameworks!

def common_pods
  pod 'Alamofire', '~> 5.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftyJSON', '~> 4.0.0'
  pod 'PromiseKit', '~> 6.0'
  pod 'Kingfisher', '~> 5.0'
  #  pod 'ImageViewer'
end

target :'SwiftDemo'  do
    common_pods
end


target 'RxSwiftDemo' do
  common_pods
  
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end
