source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'
use_frameworks!

def common_pods
  pod 'Alamofire', '~> 5.4.2'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftyJSON', '~> 5.0.1'
  # pod 'PromiseKit', '~> 6.0'
  pod 'Kingfisher', '~> 6.2'
  #  pod 'ImageViewer'
#  pod 'Starscream', '~> 4.0.0'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
end


def dev_pods
  pod 'SwiftLint', '0.43.1', configurations: ['Debug']
  pod 'SwiftGen', '6.4.0', configurations: ['Debug']
end


target 'SwiftDemo'  do
    common_pods
    dev_pods
end


target 'RxSwiftDemo' do
  
  common_pods
  
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
               end
          end
   end
end
